version: 2
updates:
  - package-ecosystem: maven
    directory: /
    schedule:
      interval: weekly
    groups:
      spring:
        patterns: ["org.springframework*"]
      testcontainers:
        patterns: ["org.testcontainers*"]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: docker-compose
    directory: /infra/compose
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /k8s/infra
    schedule:
      interval: weekly
