#!/usr/bin/env bash
# Rewrites docs/perf/README.md from every summary in docs/perf: one table per scenario, oldest first,
# and a p99 trend across the step checkpoints. bench.sh runs it; run it by hand after a run.sh.
set -euo pipefail
cd "$(dirname "$0")/.."
OUT=docs/perf/README.md

runs() { jq -s --arg s "$1" '[.[] | select(.meta.scenario == $s)] | sort_by(.meta.date)' docs/perf/"$1"-*.json; }
cell() { echo "\(.metrics[\"$1\"].values[\"$2\"]|floor)"; }
# mermaid line chart of one metric's p99 over the step* labels; GitHub renders it
chart() { runs "$1" | jq -r --arg t "$2" --arg m "$3" '
  map(select(.meta.label | startswith("step"))) | select(length > 0)
  | "```mermaid\nxychart-beta\n    title \"\($t)\"\n    x-axis [\(map("\"" + .meta.label + "\"") | join(", "))]\n    y-axis \"ms\"\n    line [\(map(.metrics[$m].values["p(99)"] | floor) | join(", "))]\n```\n"'; }

{
echo "# Performance history"
echo
echo "Every file here is one k6 run, written by \`perf/run.sh\` and stamped with the commit it measured (\`.meta\`)."
echo "\`perf/bench.sh stepNN\` runs the fixed suite at the end of every step, so the \`step*\` rows are comparable"
echo "across the whole build; the other rows are one-off experiments. \`perf/compare.sh a.json b.json\` diffs any two."
echo "Open model (k6 constant arrival rate), one machine, Postgres and Redpanda in Docker, services as local JVMs."
echo "Rows before step 15 were measured with the JIT pinned at C1 (Boot's \`spring-boot:run\` default); from step 15 the services run with C2."
echo "Generated by \`perf/history.sh\`; do not edit."
echo
echo "## Transfer: \`POST /api/v1/transfers\`, one service, one transaction"
echo
echo "| date | commit | label | load | p50 ms | p95 ms | p99 ms | failed |"
echo "|---|---|---|---|---:|---:|---:|---:|"
runs transfer | jq -r ".[] | \"| \(.meta.date[:10]) | \`\(.meta.commit)\` | \(.meta.label) | \(.meta.rate)/s for \(.meta.duration) | $(cell http_req_duration med) | $(cell http_req_duration 'p(95)') | $(cell http_req_duration 'p(99)') | \(.metrics.http_req_failed.values.rate*10000|floor/100)% |\""
echo
chart transfer "transfer p99, ms" http_req_duration
echo "## Hold: \`POST /api/v1/holds\`, ledger asks account first"
echo
echo "| date | commit | label | load | p50 ms | p95 ms | p99 ms | failed |"
echo "|---|---|---|---|---:|---:|---:|---:|"
runs holds | jq -r ".[] | \"| \(.meta.date[:10]) | \`\(.meta.commit)\` | \(.meta.label) | \(.meta.rate)/s for \(.meta.duration) | $(cell http_req_duration med) | $(cell http_req_duration 'p(95)') | $(cell http_req_duration 'p(99)') | \(.metrics.http_req_failed.values.rate*10000|floor/100)% |\""
echo
chart holds "hold p99, ms" http_req_duration
echo "## Payment: \`POST /api/v1/payments\`, the saga across four services"
echo
echo "The POST answers 202 at once; \`settled\` is the time until the saga row is Captured or Failed, read from the database (\`perf/settled.sh\`)."
echo
echo "| date | commit | label | load | POST p50 | POST p99 | settled p50 | settled p99 | captured | failed |"
echo "|---|---|---|---|---:|---:|---:|---:|---:|---:|"
runs payments | jq -r ".[] | \"| \(.meta.date[:10]) | \`\(.meta.commit)\` | \(.meta.label) | \(.meta.rate)/s for \(.meta.duration) | $(cell http_req_duration med) | $(cell http_req_duration 'p(99)') | $(cell payment_settled med) | $(cell payment_settled 'p(99)') | \(.metrics.payment_settled.values.captured) | \(.metrics.payment_settled.values.failed) |\""
echo
chart payments "payment POST p99, ms" http_req_duration
chart payments "payment settled p99, ms" payment_settled
echo "Hosts: $(jq -rs '[.[].meta.host | select(.)] | unique | join("; ")' docs/perf/*.json)."
} > "$OUT"
echo "wrote $OUT"
