namePrefix: ledger-
resources: [../../base]
labels:
  - pairs: {app: ledger}
    includeSelectors: true
images:
  - name: ledgerflow/service
    newName: ledgerflow/ledger-service
patches:
  - target: {kind: Deployment}
    patch: |
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value: {name: DB_URL, value: "jdbc:postgresql://postgres:5432/ledger"}
  - target: {kind: Service}
    patch: |
      - op: add
        path: /spec/ports/0/nodePort
        value: 30081
